/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ScriptVaultRegistry {
  export type LicenseTermsStruct = {
    workId: BigNumberish;
    licensee: AddressLike;
    terms: string;
    priceWei: BigNumberish;
    active: boolean;
  };

  export type LicenseTermsStructOutput = [
    workId: bigint,
    licensee: string,
    terms: string,
    priceWei: bigint,
    active: boolean
  ] & {
    workId: bigint;
    licensee: string;
    terms: string;
    priceWei: bigint;
    active: boolean;
  };

  export type VersionInfoStruct = {
    workId: BigNumberish;
    versionId: BigNumberish;
    title: string;
    contentHash: BytesLike;
    metadataURI: string;
    parentVersionId: BigNumberish;
    visibility: BigNumberish;
    timestamp: BigNumberish;
  };

  export type VersionInfoStructOutput = [
    workId: bigint,
    versionId: bigint,
    title: string,
    contentHash: string,
    metadataURI: string,
    parentVersionId: bigint,
    visibility: bigint,
    timestamp: bigint
  ] & {
    workId: bigint;
    versionId: bigint;
    title: string;
    contentHash: string;
    metadataURI: string;
    parentVersionId: bigint;
    visibility: bigint;
    timestamp: bigint;
  };

  export type WorkInfoStruct = {
    author: AddressLike;
    currentVersionId: BigNumberish;
    createdAt: BigNumberish;
    category: string;
  };

  export type WorkInfoStructOutput = [
    author: string,
    currentVersionId: bigint,
    createdAt: bigint,
    category: string
  ] & {
    author: string;
    currentVersionId: bigint;
    createdAt: bigint;
    category: string;
  };
}

export interface ScriptVaultRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accessGrants"
      | "buyLicense"
      | "downgradeScope"
      | "getEncryptedScope"
      | "getLicense"
      | "getVersion"
      | "getWorkInfo"
      | "getWorkLicenses"
      | "getWorkVersions"
      | "getWorkVersionsCount"
      | "grantAccess"
      | "isAccessGranted"
      | "issueLicense"
      | "licenses"
      | "nextLicenseId"
      | "nextVersionId"
      | "nextWorkId"
      | "protocolId"
      | "revokeAccess"
      | "submitVersion"
      | "upgradeScope"
      | "versions"
      | "workLicenses"
      | "workVersions"
      | "works"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessRevoked"
      | "CopyrightNFTMinted"
      | "LicenseCreated"
      | "LicenseIssued"
      | "VersionCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accessGrants",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyLicense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "downgradeScope",
    values: [BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedScope",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLicense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkLicenses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkVersions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkVersionsCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAccessGranted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueLicense",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "licenses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextLicenseId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextVersionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextWorkId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVersion",
    values: [
      BigNumberish,
      string,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeScope",
    values: [BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "versions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "workLicenses",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "workVersions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "works", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "accessGrants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyLicense", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "downgradeScope",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedScope",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLicense", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWorkInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkLicenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkVersions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkVersionsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAccessGranted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "licenses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextLicenseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextVersionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextWorkId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeScope",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "versions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "workLicenses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workVersions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "works", data: BytesLike): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    workId: BigNumberish,
    grantee: AddressLike,
    granter: AddressLike,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    workId: bigint,
    grantee: string,
    granter: string,
    expiry: bigint
  ];
  export interface OutputObject {
    workId: bigint;
    grantee: string;
    granter: string;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [
    workId: BigNumberish,
    grantee: AddressLike,
    revoker: AddressLike
  ];
  export type OutputTuple = [workId: bigint, grantee: string, revoker: string];
  export interface OutputObject {
    workId: bigint;
    grantee: string;
    revoker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CopyrightNFTMintedEvent {
  export type InputTuple = [
    workId: BigNumberish,
    versionId: BigNumberish,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    workId: bigint,
    versionId: bigint,
    tokenId: bigint
  ];
  export interface OutputObject {
    workId: bigint;
    versionId: bigint;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseCreatedEvent {
  export type InputTuple = [
    workId: BigNumberish,
    licenseId: BigNumberish,
    terms: string,
    priceWei: BigNumberish
  ];
  export type OutputTuple = [
    workId: bigint,
    licenseId: bigint,
    terms: string,
    priceWei: bigint
  ];
  export interface OutputObject {
    workId: bigint;
    licenseId: bigint;
    terms: string;
    priceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseIssuedEvent {
  export type InputTuple = [
    workId: BigNumberish,
    licensee: AddressLike,
    licenseId: BigNumberish,
    terms: string,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    workId: bigint,
    licensee: string,
    licenseId: bigint,
    terms: string,
    amount: bigint
  ];
  export interface OutputObject {
    workId: bigint;
    licensee: string;
    licenseId: bigint;
    terms: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VersionCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    workId: BigNumberish,
    versionId: BigNumberish,
    title: string,
    hash: BytesLike,
    metadataURI: string,
    visibility: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    workId: bigint,
    versionId: bigint,
    title: string,
    hash: string,
    metadataURI: string,
    visibility: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    creator: string;
    workId: bigint;
    versionId: bigint;
    title: string;
    hash: string;
    metadataURI: string;
    visibility: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ScriptVaultRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ScriptVaultRegistry;
  waitForDeployment(): Promise<this>;

  interface: ScriptVaultRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accessGrants: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, bigint] & { granted: boolean; expiry: bigint }],
    "view"
  >;

  buyLicense: TypedContractMethod<[licenseId: BigNumberish], [void], "payable">;

  downgradeScope: TypedContractMethod<
    [
      workId: BigNumberish,
      grantee: AddressLike,
      scopeExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEncryptedScope: TypedContractMethod<
    [workId: BigNumberish, grantee: AddressLike],
    [string],
    "view"
  >;

  getLicense: TypedContractMethod<
    [licenseId: BigNumberish],
    [ScriptVaultRegistry.LicenseTermsStructOutput],
    "view"
  >;

  getVersion: TypedContractMethod<
    [versionId: BigNumberish],
    [ScriptVaultRegistry.VersionInfoStructOutput],
    "view"
  >;

  getWorkInfo: TypedContractMethod<
    [workId: BigNumberish],
    [ScriptVaultRegistry.WorkInfoStructOutput],
    "view"
  >;

  getWorkLicenses: TypedContractMethod<
    [workId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getWorkVersions: TypedContractMethod<
    [workId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getWorkVersionsCount: TypedContractMethod<
    [workId: BigNumberish],
    [bigint],
    "view"
  >;

  grantAccess: TypedContractMethod<
    [
      workId: BigNumberish,
      grantee: AddressLike,
      expiry: BigNumberish,
      scopeExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  isAccessGranted: TypedContractMethod<
    [workId: BigNumberish, grantee: AddressLike],
    [boolean],
    "view"
  >;

  issueLicense: TypedContractMethod<
    [workId: BigNumberish, terms: string, priceWei: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  licenses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        workId: bigint;
        licensee: string;
        terms: string;
        priceWei: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  nextLicenseId: TypedContractMethod<[], [bigint], "view">;

  nextVersionId: TypedContractMethod<[], [bigint], "view">;

  nextWorkId: TypedContractMethod<[], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  revokeAccess: TypedContractMethod<
    [workId: BigNumberish, grantee: AddressLike],
    [void],
    "nonpayable"
  >;

  submitVersion: TypedContractMethod<
    [
      maybeWorkId: BigNumberish,
      title: string,
      contentHash: BytesLike,
      metadataURI: string,
      parentVersionId: BigNumberish,
      visibility: BigNumberish,
      category: string
    ],
    [[bigint, bigint] & { workId: bigint; versionId: bigint }],
    "nonpayable"
  >;

  upgradeScope: TypedContractMethod<
    [
      workId: BigNumberish,
      grantee: AddressLike,
      scopeExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  versions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, bigint, bigint] & {
        workId: bigint;
        versionId: bigint;
        title: string;
        contentHash: string;
        metadataURI: string;
        parentVersionId: bigint;
        visibility: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  workLicenses: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  workVersions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  works: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        author: string;
        currentVersionId: bigint;
        createdAt: bigint;
        category: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accessGrants"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[boolean, bigint] & { granted: boolean; expiry: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "buyLicense"
  ): TypedContractMethod<[licenseId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "downgradeScope"
  ): TypedContractMethod<
    [
      workId: BigNumberish,
      grantee: AddressLike,
      scopeExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedScope"
  ): TypedContractMethod<
    [workId: BigNumberish, grantee: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLicense"
  ): TypedContractMethod<
    [licenseId: BigNumberish],
    [ScriptVaultRegistry.LicenseTermsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVersion"
  ): TypedContractMethod<
    [versionId: BigNumberish],
    [ScriptVaultRegistry.VersionInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkInfo"
  ): TypedContractMethod<
    [workId: BigNumberish],
    [ScriptVaultRegistry.WorkInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkLicenses"
  ): TypedContractMethod<[workId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getWorkVersions"
  ): TypedContractMethod<[workId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getWorkVersionsCount"
  ): TypedContractMethod<[workId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [
      workId: BigNumberish,
      grantee: AddressLike,
      expiry: BigNumberish,
      scopeExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAccessGranted"
  ): TypedContractMethod<
    [workId: BigNumberish, grantee: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueLicense"
  ): TypedContractMethod<
    [workId: BigNumberish, terms: string, priceWei: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "licenses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean] & {
        workId: bigint;
        licensee: string;
        terms: string;
        priceWei: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextLicenseId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextVersionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextWorkId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [workId: BigNumberish, grantee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitVersion"
  ): TypedContractMethod<
    [
      maybeWorkId: BigNumberish,
      title: string,
      contentHash: BytesLike,
      metadataURI: string,
      parentVersionId: BigNumberish,
      visibility: BigNumberish,
      category: string
    ],
    [[bigint, bigint] & { workId: bigint; versionId: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeScope"
  ): TypedContractMethod<
    [
      workId: BigNumberish,
      grantee: AddressLike,
      scopeExt: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "versions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, bigint, bigint] & {
        workId: bigint;
        versionId: bigint;
        title: string;
        contentHash: string;
        metadataURI: string;
        parentVersionId: bigint;
        visibility: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "workLicenses"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "workVersions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "works"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string] & {
        author: string;
        currentVersionId: bigint;
        createdAt: bigint;
        category: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CopyrightNFTMinted"
  ): TypedContractEvent<
    CopyrightNFTMintedEvent.InputTuple,
    CopyrightNFTMintedEvent.OutputTuple,
    CopyrightNFTMintedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseCreated"
  ): TypedContractEvent<
    LicenseCreatedEvent.InputTuple,
    LicenseCreatedEvent.OutputTuple,
    LicenseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseIssued"
  ): TypedContractEvent<
    LicenseIssuedEvent.InputTuple,
    LicenseIssuedEvent.OutputTuple,
    LicenseIssuedEvent.OutputObject
  >;
  getEvent(
    key: "VersionCreated"
  ): TypedContractEvent<
    VersionCreatedEvent.InputTuple,
    VersionCreatedEvent.OutputTuple,
    VersionCreatedEvent.OutputObject
  >;

  filters: {
    "AccessGranted(uint256,address,address,uint64)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessRevoked(uint256,address,address)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "CopyrightNFTMinted(uint256,uint256,uint256)": TypedContractEvent<
      CopyrightNFTMintedEvent.InputTuple,
      CopyrightNFTMintedEvent.OutputTuple,
      CopyrightNFTMintedEvent.OutputObject
    >;
    CopyrightNFTMinted: TypedContractEvent<
      CopyrightNFTMintedEvent.InputTuple,
      CopyrightNFTMintedEvent.OutputTuple,
      CopyrightNFTMintedEvent.OutputObject
    >;

    "LicenseCreated(uint256,uint256,string,uint256)": TypedContractEvent<
      LicenseCreatedEvent.InputTuple,
      LicenseCreatedEvent.OutputTuple,
      LicenseCreatedEvent.OutputObject
    >;
    LicenseCreated: TypedContractEvent<
      LicenseCreatedEvent.InputTuple,
      LicenseCreatedEvent.OutputTuple,
      LicenseCreatedEvent.OutputObject
    >;

    "LicenseIssued(uint256,address,uint256,string,uint256)": TypedContractEvent<
      LicenseIssuedEvent.InputTuple,
      LicenseIssuedEvent.OutputTuple,
      LicenseIssuedEvent.OutputObject
    >;
    LicenseIssued: TypedContractEvent<
      LicenseIssuedEvent.InputTuple,
      LicenseIssuedEvent.OutputTuple,
      LicenseIssuedEvent.OutputObject
    >;

    "VersionCreated(address,uint256,uint256,string,bytes32,string,uint8,uint64)": TypedContractEvent<
      VersionCreatedEvent.InputTuple,
      VersionCreatedEvent.OutputTuple,
      VersionCreatedEvent.OutputObject
    >;
    VersionCreated: TypedContractEvent<
      VersionCreatedEvent.InputTuple,
      VersionCreatedEvent.OutputTuple,
      VersionCreatedEvent.OutputObject
    >;
  };
}
